[metadata]
name = coreomics-fs
version = 0.1.0

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    coreomics = coreomics_fs.cli.project_cli:main
    coreomics-build = coreomics_fs.build.build_views:main
    coreomics-fetch = coreomics_fs.build.fetch_projects:main
