[paths]
; where <year>/<month>/<ID> lives
canonical_root = /data/projects
; top-level view container
views_root = /data/views
; version folder name
submissions_db_directory = /data/.submissions_db
date_format = %%Y_%%m_%%d
; per-run log file (inside version dir)
log_name = build.log
; per-run error log (inside version dir)
error_log = error.log    

[api]
api_key = API_KEY_HERE
api_base_url = my.submission.system.com

[retain]
daily = 7
weekly = 4 
monthly = 2